// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/usr_dto/admin.proto

package usr_dto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AdminLoginRequest struct {
	Number               string   `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminLoginRequest) Reset()         { *m = AdminLoginRequest{} }
func (m *AdminLoginRequest) String() string { return proto.CompactTextString(m) }
func (*AdminLoginRequest) ProtoMessage()    {}
func (*AdminLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_069634035deb7e63, []int{0}
}

func (m *AdminLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminLoginRequest.Unmarshal(m, b)
}
func (m *AdminLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminLoginRequest.Marshal(b, m, deterministic)
}
func (m *AdminLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminLoginRequest.Merge(m, src)
}
func (m *AdminLoginRequest) XXX_Size() int {
	return xxx_messageInfo_AdminLoginRequest.Size(m)
}
func (m *AdminLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminLoginRequest proto.InternalMessageInfo

func (m *AdminLoginRequest) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *AdminLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AdminLoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminLoginResponse) Reset()         { *m = AdminLoginResponse{} }
func (m *AdminLoginResponse) String() string { return proto.CompactTextString(m) }
func (*AdminLoginResponse) ProtoMessage()    {}
func (*AdminLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_069634035deb7e63, []int{1}
}

func (m *AdminLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminLoginResponse.Unmarshal(m, b)
}
func (m *AdminLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminLoginResponse.Marshal(b, m, deterministic)
}
func (m *AdminLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminLoginResponse.Merge(m, src)
}
func (m *AdminLoginResponse) XXX_Size() int {
	return xxx_messageInfo_AdminLoginResponse.Size(m)
}
func (m *AdminLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdminLoginResponse proto.InternalMessageInfo

func (m *AdminLoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AdminLoginResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterType((*AdminLoginRequest)(nil), "usr_dto.AdminLoginRequest")
	proto.RegisterType((*AdminLoginResponse)(nil), "usr_dto.AdminLoginResponse")
}

func init() { proto.RegisterFile("grpc/usr_dto/admin.proto", fileDescriptor_069634035deb7e63) }

var fileDescriptor_069634035deb7e63 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xbd, 0x4a, 0xc5, 0x40,
	0x10, 0x46, 0xb9, 0x82, 0x57, 0xdd, 0xce, 0x45, 0x24, 0x58, 0x49, 0x2a, 0x9b, 0x24, 0x85, 0x4f,
	0xa0, 0x85, 0x36, 0x56, 0xe9, 0xd4, 0x42, 0xf6, 0x67, 0x48, 0x16, 0xb3, 0x33, 0xeb, 0xcc, 0xae,
	0xbe, 0xbe, 0x24, 0x26, 0xa2, 0x70, 0xcb, 0x73, 0x06, 0x0e, 0xcc, 0xa7, 0xaa, 0x81, 0x93, 0xeb,
	0x8a, 0xf0, 0x9b, 0xcf, 0xd4, 0x19, 0x1f, 0x03, 0xb6, 0x89, 0x29, 0x93, 0x3e, 0x59, 0x65, 0xfd,
	0xa8, 0xce, 0xef, 0x66, 0xff, 0x44, 0x43, 0xc0, 0x1e, 0x3e, 0x0a, 0x48, 0xd6, 0x97, 0x6a, 0x8f,
	0x25, 0x5a, 0xe0, 0x6a, 0x77, 0xbd, 0xbb, 0x39, 0xeb, 0x57, 0xd2, 0x57, 0xea, 0x34, 0x19, 0x91,
	0x2f, 0x62, 0x5f, 0x1d, 0x2d, 0x97, 0x5f, 0xae, 0x1f, 0x94, 0xfe, 0x1b, 0x92, 0x44, 0x28, 0xa0,
	0x2f, 0xd4, 0x71, 0xa6, 0x77, 0xc0, 0x35, 0xf4, 0x03, 0x73, 0xa7, 0x08, 0x30, 0x9a, 0x08, 0x5b,
	0x67, 0xe3, 0xfb, 0xd7, 0x97, 0xe7, 0x21, 0xe4, 0xb1, 0xd8, 0xd6, 0x51, 0xec, 0x26, 0x88, 0x84,
	0x8d, 0x9b, 0xa8, 0xf8, 0x46, 0x80, 0x3f, 0x83, 0x83, 0x7f, 0xce, 0x1b, 0x19, 0x2d, 0x19, 0xf6,
	0x87, 0x6d, 0xe3, 0x28, 0x46, 0xc2, 0x6d, 0x02, 0xbb, 0x5f, 0xbe, 0xbf, 0xfd, 0x0e, 0x00, 0x00,
	0xff, 0xff, 0x51, 0x00, 0x59, 0x53, 0x19, 0x01, 0x00, 0x00,
}
