// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/adm_dto/administrator.proto

package adm_dto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AdministratorLoginRequestDto struct {
	Number               string   `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdministratorLoginRequestDto) Reset()         { *m = AdministratorLoginRequestDto{} }
func (m *AdministratorLoginRequestDto) String() string { return proto.CompactTextString(m) }
func (*AdministratorLoginRequestDto) ProtoMessage()    {}
func (*AdministratorLoginRequestDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbfd3d168ba0078c, []int{0}
}

func (m *AdministratorLoginRequestDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdministratorLoginRequestDto.Unmarshal(m, b)
}
func (m *AdministratorLoginRequestDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdministratorLoginRequestDto.Marshal(b, m, deterministic)
}
func (m *AdministratorLoginRequestDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdministratorLoginRequestDto.Merge(m, src)
}
func (m *AdministratorLoginRequestDto) XXX_Size() int {
	return xxx_messageInfo_AdministratorLoginRequestDto.Size(m)
}
func (m *AdministratorLoginRequestDto) XXX_DiscardUnknown() {
	xxx_messageInfo_AdministratorLoginRequestDto.DiscardUnknown(m)
}

var xxx_messageInfo_AdministratorLoginRequestDto proto.InternalMessageInfo

func (m *AdministratorLoginRequestDto) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *AdministratorLoginRequestDto) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AdministratorLoginResponseDto struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdministratorLoginResponseDto) Reset()         { *m = AdministratorLoginResponseDto{} }
func (m *AdministratorLoginResponseDto) String() string { return proto.CompactTextString(m) }
func (*AdministratorLoginResponseDto) ProtoMessage()    {}
func (*AdministratorLoginResponseDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbfd3d168ba0078c, []int{1}
}

func (m *AdministratorLoginResponseDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdministratorLoginResponseDto.Unmarshal(m, b)
}
func (m *AdministratorLoginResponseDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdministratorLoginResponseDto.Marshal(b, m, deterministic)
}
func (m *AdministratorLoginResponseDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdministratorLoginResponseDto.Merge(m, src)
}
func (m *AdministratorLoginResponseDto) XXX_Size() int {
	return xxx_messageInfo_AdministratorLoginResponseDto.Size(m)
}
func (m *AdministratorLoginResponseDto) XXX_DiscardUnknown() {
	xxx_messageInfo_AdministratorLoginResponseDto.DiscardUnknown(m)
}

var xxx_messageInfo_AdministratorLoginResponseDto proto.InternalMessageInfo

func (m *AdministratorLoginResponseDto) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*AdministratorLoginRequestDto)(nil), "adm_dto.AdministratorLoginRequestDto")
	proto.RegisterType((*AdministratorLoginResponseDto)(nil), "adm_dto.AdministratorLoginResponseDto")
}

func init() { proto.RegisterFile("grpc/adm_dto/administrator.proto", fileDescriptor_dbfd3d168ba0078c) }

var fileDescriptor_dbfd3d168ba0078c = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xbd, 0x4a, 0xc5, 0x40,
	0x10, 0x46, 0xb9, 0x82, 0x57, 0xdd, 0x32, 0x88, 0x04, 0x51, 0x08, 0xa9, 0x6c, 0x92, 0x14, 0xe2,
	0x03, 0x28, 0x96, 0x56, 0xe9, 0xd4, 0x42, 0xf6, 0x67, 0x48, 0x16, 0xb3, 0x3b, 0xeb, 0xcc, 0xac,
	0xbe, 0xbe, 0x24, 0x46, 0xf1, 0x42, 0xaa, 0xe5, 0x7c, 0x07, 0x0e, 0xec, 0xa8, 0x6a, 0xa0, 0x64,
	0x3b, 0xed, 0xc2, 0x9b, 0x13, 0x9c, 0x5f, 0x1f, 0x3d, 0x0b, 0x69, 0x41, 0x6a, 0x13, 0xa1, 0x60,
	0x71, 0xb2, 0xca, 0xba, 0x57, 0x57, 0xf7, 0xff, 0xfd, 0x13, 0x0e, 0x3e, 0xf6, 0xf0, 0x91, 0x81,
	0xe5, 0x51, 0xb0, 0xb8, 0x50, 0xfb, 0x98, 0x83, 0x01, 0x2a, 0x77, 0xd5, 0xee, 0xe6, 0xac, 0x5f,
	0xa9, 0xb8, 0x54, 0xa7, 0x49, 0x33, 0x7f, 0x21, 0xb9, 0xf2, 0x68, 0x31, 0x7f, 0x5c, 0xdf, 0xa9,
	0xeb, 0xad, 0x26, 0x27, 0x8c, 0x0c, 0x73, 0xf4, 0x5c, 0x1d, 0x0b, 0xbe, 0x43, 0x5c, 0x9b, 0x3f,
	0xf0, 0xf0, 0xfa, 0xf2, 0x3c, 0x78, 0x19, 0xb3, 0x69, 0x2d, 0x86, 0x6e, 0x82, 0x80, 0xb1, 0xb1,
	0x13, 0x66, 0xd7, 0x30, 0xd0, 0xa7, 0xb7, 0x70, 0xb0, 0x39, 0xcd, 0xa3, 0x41, 0x4d, 0x6e, 0x7b,
	0x6d, 0x2c, 0x86, 0x80, 0xf1, 0xf7, 0x08, 0x66, 0xbf, 0xfc, 0xfb, 0xf6, 0x3b, 0x00, 0x00, 0xff,
	0xff, 0xc5, 0x24, 0xc8, 0x17, 0x1b, 0x01, 0x00, 0x00,
}
