// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/adm_dto/service.proto

package adm_dto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServiceInfoDto struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Introduce            string   `protobuf:"bytes,3,opt,name=introduce,proto3" json:"introduce,omitempty"`
	ServiceIcon          string   `protobuf:"bytes,4,opt,name=service_icon,json=serviceIcon,proto3" json:"service_icon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceInfoDto) Reset()         { *m = ServiceInfoDto{} }
func (m *ServiceInfoDto) String() string { return proto.CompactTextString(m) }
func (*ServiceInfoDto) ProtoMessage()    {}
func (*ServiceInfoDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9857153d4e6eb0b4, []int{0}
}

func (m *ServiceInfoDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceInfoDto.Unmarshal(m, b)
}
func (m *ServiceInfoDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceInfoDto.Marshal(b, m, deterministic)
}
func (m *ServiceInfoDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceInfoDto.Merge(m, src)
}
func (m *ServiceInfoDto) XXX_Size() int {
	return xxx_messageInfo_ServiceInfoDto.Size(m)
}
func (m *ServiceInfoDto) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceInfoDto.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceInfoDto proto.InternalMessageInfo

func (m *ServiceInfoDto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceInfoDto) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *ServiceInfoDto) GetIntroduce() string {
	if m != nil {
		return m.Introduce
	}
	return ""
}

func (m *ServiceInfoDto) GetServiceIcon() string {
	if m != nil {
		return m.ServiceIcon
	}
	return ""
}

type OnlineServiceInfoDto struct {
	EndpointHost          string   `protobuf:"bytes,1,opt,name=endpoint_host,json=endpointHost,proto3" json:"endpoint_host,omitempty"`
	EndpointPort          uint32   `protobuf:"varint,2,opt,name=endpoint_port,json=endpointPort,proto3" json:"endpoint_port,omitempty"`
	ApplicationVersion    string   `protobuf:"bytes,3,opt,name=application_version,json=applicationVersion,proto3" json:"application_version,omitempty"`
	ApplicationVersionNum uint32   `protobuf:"varint,4,opt,name=application_version_num,json=applicationVersionNum,proto3" json:"application_version_num,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *OnlineServiceInfoDto) Reset()         { *m = OnlineServiceInfoDto{} }
func (m *OnlineServiceInfoDto) String() string { return proto.CompactTextString(m) }
func (*OnlineServiceInfoDto) ProtoMessage()    {}
func (*OnlineServiceInfoDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9857153d4e6eb0b4, []int{1}
}

func (m *OnlineServiceInfoDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlineServiceInfoDto.Unmarshal(m, b)
}
func (m *OnlineServiceInfoDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlineServiceInfoDto.Marshal(b, m, deterministic)
}
func (m *OnlineServiceInfoDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlineServiceInfoDto.Merge(m, src)
}
func (m *OnlineServiceInfoDto) XXX_Size() int {
	return xxx_messageInfo_OnlineServiceInfoDto.Size(m)
}
func (m *OnlineServiceInfoDto) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlineServiceInfoDto.DiscardUnknown(m)
}

var xxx_messageInfo_OnlineServiceInfoDto proto.InternalMessageInfo

func (m *OnlineServiceInfoDto) GetEndpointHost() string {
	if m != nil {
		return m.EndpointHost
	}
	return ""
}

func (m *OnlineServiceInfoDto) GetEndpointPort() uint32 {
	if m != nil {
		return m.EndpointPort
	}
	return 0
}

func (m *OnlineServiceInfoDto) GetApplicationVersion() string {
	if m != nil {
		return m.ApplicationVersion
	}
	return ""
}

func (m *OnlineServiceInfoDto) GetApplicationVersionNum() uint32 {
	if m != nil {
		return m.ApplicationVersionNum
	}
	return 0
}

type ServiceStatusDto struct {
	Info                 *ServiceInfoDto         `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	OnlineInfoList       []*OnlineServiceInfoDto `protobuf:"bytes,2,rep,name=online_info_list,json=onlineInfoList,proto3" json:"online_info_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ServiceStatusDto) Reset()         { *m = ServiceStatusDto{} }
func (m *ServiceStatusDto) String() string { return proto.CompactTextString(m) }
func (*ServiceStatusDto) ProtoMessage()    {}
func (*ServiceStatusDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9857153d4e6eb0b4, []int{2}
}

func (m *ServiceStatusDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceStatusDto.Unmarshal(m, b)
}
func (m *ServiceStatusDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceStatusDto.Marshal(b, m, deterministic)
}
func (m *ServiceStatusDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceStatusDto.Merge(m, src)
}
func (m *ServiceStatusDto) XXX_Size() int {
	return xxx_messageInfo_ServiceStatusDto.Size(m)
}
func (m *ServiceStatusDto) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceStatusDto.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceStatusDto proto.InternalMessageInfo

func (m *ServiceStatusDto) GetInfo() *ServiceInfoDto {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ServiceStatusDto) GetOnlineInfoList() []*OnlineServiceInfoDto {
	if m != nil {
		return m.OnlineInfoList
	}
	return nil
}

type AllServiceStatusDto struct {
	AllServiceStatusList []*ServiceStatusDto `protobuf:"bytes,1,rep,name=all_service_status_list,json=allServiceStatusList,proto3" json:"all_service_status_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AllServiceStatusDto) Reset()         { *m = AllServiceStatusDto{} }
func (m *AllServiceStatusDto) String() string { return proto.CompactTextString(m) }
func (*AllServiceStatusDto) ProtoMessage()    {}
func (*AllServiceStatusDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9857153d4e6eb0b4, []int{3}
}

func (m *AllServiceStatusDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllServiceStatusDto.Unmarshal(m, b)
}
func (m *AllServiceStatusDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllServiceStatusDto.Marshal(b, m, deterministic)
}
func (m *AllServiceStatusDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllServiceStatusDto.Merge(m, src)
}
func (m *AllServiceStatusDto) XXX_Size() int {
	return xxx_messageInfo_AllServiceStatusDto.Size(m)
}
func (m *AllServiceStatusDto) XXX_DiscardUnknown() {
	xxx_messageInfo_AllServiceStatusDto.DiscardUnknown(m)
}

var xxx_messageInfo_AllServiceStatusDto proto.InternalMessageInfo

func (m *AllServiceStatusDto) GetAllServiceStatusList() []*ServiceStatusDto {
	if m != nil {
		return m.AllServiceStatusList
	}
	return nil
}

func init() {
	proto.RegisterType((*ServiceInfoDto)(nil), "adm_dto.ServiceInfoDto")
	proto.RegisterType((*OnlineServiceInfoDto)(nil), "adm_dto.OnlineServiceInfoDto")
	proto.RegisterType((*ServiceStatusDto)(nil), "adm_dto.ServiceStatusDto")
	proto.RegisterType((*AllServiceStatusDto)(nil), "adm_dto.AllServiceStatusDto")
}

func init() { proto.RegisterFile("grpc/adm_dto/service.proto", fileDescriptor_9857153d4e6eb0b4) }

var fileDescriptor_9857153d4e6eb0b4 = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xdf, 0xea, 0xd3, 0x30,
	0x18, 0xa5, 0x6e, 0x28, 0xcb, 0xfe, 0x30, 0xb2, 0xc9, 0xaa, 0x28, 0x68, 0xbd, 0x19, 0xc8, 0x5a,
	0x98, 0xe0, 0xbd, 0x22, 0xe8, 0x40, 0x74, 0x74, 0x20, 0xa8, 0x17, 0x21, 0x4b, 0xb3, 0x2e, 0x90,
	0xe4, 0x2b, 0x49, 0x3a, 0x5f, 0xc1, 0x57, 0xf3, 0xad, 0xa4, 0x69, 0xb6, 0xfd, 0xf6, 0xe7, 0x2e,
	0x39, 0xdf, 0x39, 0x3d, 0xe7, 0x7c, 0x0d, 0x7a, 0x5e, 0x9a, 0x8a, 0x65, 0xb4, 0x50, 0xa4, 0x70,
	0x90, 0x59, 0x6e, 0x0e, 0x82, 0xf1, 0xb4, 0x32, 0xe0, 0x00, 0x3f, 0x09, 0x70, 0xf2, 0x07, 0x8d,
	0x36, 0xed, 0x64, 0xa5, 0x77, 0xf0, 0xc9, 0x01, 0xc6, 0xa8, 0xab, 0xa9, 0xe2, 0x71, 0xf4, 0x2a,
	0x9a, 0xf7, 0x72, 0x7f, 0xc6, 0x63, 0xd4, 0x71, 0xb4, 0x8c, 0x1f, 0x79, 0xa8, 0x39, 0xe2, 0x17,
	0xa8, 0x27, 0xb4, 0x33, 0x50, 0xd4, 0x8c, 0xc7, 0x1d, 0x8f, 0x9f, 0x01, 0xfc, 0x1a, 0x0d, 0x82,
	0x1f, 0x11, 0x0c, 0x74, 0xdc, 0xf5, 0x84, 0x7e, 0xc0, 0x56, 0x0c, 0x74, 0xf2, 0x2f, 0x42, 0xd3,
	0xef, 0x5a, 0x0a, 0xcd, 0xaf, 0xfc, 0xdf, 0xa0, 0x21, 0xd7, 0x45, 0x05, 0x42, 0x3b, 0xb2, 0x07,
	0xeb, 0x42, 0x90, 0xc1, 0x11, 0xfc, 0x02, 0xd6, 0x5d, 0x90, 0x2a, 0x30, 0xce, 0x47, 0x1b, 0x9e,
	0x49, 0x6b, 0x30, 0x0e, 0x67, 0x68, 0x42, 0xab, 0x4a, 0x0a, 0x46, 0x9d, 0x00, 0x4d, 0x0e, 0xdc,
	0x58, 0x01, 0x3a, 0xa4, 0xc5, 0x0f, 0x46, 0x3f, 0xda, 0x09, 0x7e, 0x8f, 0x66, 0x77, 0x04, 0x44,
	0xd7, 0xca, 0x37, 0x18, 0xe6, 0x4f, 0x6f, 0x45, 0xdf, 0x6a, 0x95, 0xfc, 0x8d, 0xd0, 0x38, 0xb4,
	0xd8, 0x38, 0xea, 0x6a, 0xdb, 0xf4, 0x78, 0x8b, 0xba, 0x42, 0xef, 0xc0, 0xc7, 0xef, 0x2f, 0x67,
	0x69, 0xd8, 0x78, 0x7a, 0x59, 0x37, 0xf7, 0x24, 0xfc, 0x19, 0x8d, 0xc1, 0x2f, 0x83, 0x34, 0x57,
	0x22, 0x85, 0x6d, 0x2a, 0x75, 0xe6, 0xfd, 0xe5, 0xcb, 0x93, 0xf0, 0xde, 0xb6, 0xf2, 0x51, 0x2b,
	0x6b, 0xae, 0x5f, 0x85, 0x75, 0x49, 0x89, 0x26, 0x1f, 0xa4, 0xbc, 0x09, 0xb3, 0x46, 0x33, 0x2a,
	0x25, 0x39, 0xfe, 0x14, 0xeb, 0x07, 0xad, 0x4d, 0xe4, 0x6d, 0x9e, 0x5d, 0xe7, 0x3b, 0x69, 0xf3,
	0x29, 0xbd, 0xfa, 0x60, 0x63, 0xf4, 0xf1, 0xf7, 0xaf, 0x9f, 0xa5, 0x70, 0xfb, 0x7a, 0x9b, 0x32,
	0x50, 0x99, 0xe4, 0x0a, 0xf4, 0x82, 0x49, 0xa8, 0x8b, 0x45, 0x30, 0xb9, 0xc0, 0x0a, 0x6a, 0xf7,
	0x5b, 0xa0, 0xa6, 0xb8, 0x8f, 0x2e, 0x18, 0x28, 0x05, 0xfa, 0xf8, 0x58, 0xb7, 0x8f, 0xfd, 0x2b,
	0x7d, 0xf7, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x3c, 0xdb, 0x30, 0x2b, 0xc3, 0x02, 0x00, 0x00,
}
