// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/adm_dto/service.proto

package adm_dto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServiceManagementModuleDto struct {
	ModuleName           string   `protobuf:"bytes,1,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	ModuleKey            string   `protobuf:"bytes,2,opt,name=module_key,json=moduleKey,proto3" json:"module_key,omitempty"`
	ModuleIntroduce      string   `protobuf:"bytes,3,opt,name=module_introduce,json=moduleIntroduce,proto3" json:"module_introduce,omitempty"`
	ModuleIconUrl        string   `protobuf:"bytes,4,opt,name=module_icon_url,json=moduleIconUrl,proto3" json:"module_icon_url,omitempty"`
	IndexUrl             string   `protobuf:"bytes,5,opt,name=index_url,json=indexUrl,proto3" json:"index_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceManagementModuleDto) Reset()         { *m = ServiceManagementModuleDto{} }
func (m *ServiceManagementModuleDto) String() string { return proto.CompactTextString(m) }
func (*ServiceManagementModuleDto) ProtoMessage()    {}
func (*ServiceManagementModuleDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9857153d4e6eb0b4, []int{0}
}

func (m *ServiceManagementModuleDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceManagementModuleDto.Unmarshal(m, b)
}
func (m *ServiceManagementModuleDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceManagementModuleDto.Marshal(b, m, deterministic)
}
func (m *ServiceManagementModuleDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceManagementModuleDto.Merge(m, src)
}
func (m *ServiceManagementModuleDto) XXX_Size() int {
	return xxx_messageInfo_ServiceManagementModuleDto.Size(m)
}
func (m *ServiceManagementModuleDto) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceManagementModuleDto.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceManagementModuleDto proto.InternalMessageInfo

func (m *ServiceManagementModuleDto) GetModuleName() string {
	if m != nil {
		return m.ModuleName
	}
	return ""
}

func (m *ServiceManagementModuleDto) GetModuleKey() string {
	if m != nil {
		return m.ModuleKey
	}
	return ""
}

func (m *ServiceManagementModuleDto) GetModuleIntroduce() string {
	if m != nil {
		return m.ModuleIntroduce
	}
	return ""
}

func (m *ServiceManagementModuleDto) GetModuleIconUrl() string {
	if m != nil {
		return m.ModuleIconUrl
	}
	return ""
}

func (m *ServiceManagementModuleDto) GetIndexUrl() string {
	if m != nil {
		return m.IndexUrl
	}
	return ""
}

type ServiceBaseInfoDto struct {
	// 这部分是从注册中心中读取到的其他服务信息
	ServiceKey       string `protobuf:"bytes,1,opt,name=service_key,json=serviceKey,proto3" json:"service_key,omitempty"`
	ServiceName      string `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceIntroduce string `protobuf:"bytes,3,opt,name=service_introduce,json=serviceIntroduce,proto3" json:"service_introduce,omitempty"`
	// 以下是dashboard服务根据下载到的服务UI模块检索生成的
	ServiceIconUrl       string                        `protobuf:"bytes,51,opt,name=service_icon_url,json=serviceIconUrl,proto3" json:"service_icon_url,omitempty"`
	ManagementModuleList []*ServiceManagementModuleDto `protobuf:"bytes,52,rep,name=management_module_list,json=managementModuleList,proto3" json:"management_module_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ServiceBaseInfoDto) Reset()         { *m = ServiceBaseInfoDto{} }
func (m *ServiceBaseInfoDto) String() string { return proto.CompactTextString(m) }
func (*ServiceBaseInfoDto) ProtoMessage()    {}
func (*ServiceBaseInfoDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9857153d4e6eb0b4, []int{1}
}

func (m *ServiceBaseInfoDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceBaseInfoDto.Unmarshal(m, b)
}
func (m *ServiceBaseInfoDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceBaseInfoDto.Marshal(b, m, deterministic)
}
func (m *ServiceBaseInfoDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceBaseInfoDto.Merge(m, src)
}
func (m *ServiceBaseInfoDto) XXX_Size() int {
	return xxx_messageInfo_ServiceBaseInfoDto.Size(m)
}
func (m *ServiceBaseInfoDto) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceBaseInfoDto.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceBaseInfoDto proto.InternalMessageInfo

func (m *ServiceBaseInfoDto) GetServiceKey() string {
	if m != nil {
		return m.ServiceKey
	}
	return ""
}

func (m *ServiceBaseInfoDto) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *ServiceBaseInfoDto) GetServiceIntroduce() string {
	if m != nil {
		return m.ServiceIntroduce
	}
	return ""
}

func (m *ServiceBaseInfoDto) GetServiceIconUrl() string {
	if m != nil {
		return m.ServiceIconUrl
	}
	return ""
}

func (m *ServiceBaseInfoDto) GetManagementModuleList() []*ServiceManagementModuleDto {
	if m != nil {
		return m.ManagementModuleList
	}
	return nil
}

type ServiceApplicationInfoDto struct {
	ApplicationVersion    string   `protobuf:"bytes,1,opt,name=application_version,json=applicationVersion,proto3" json:"application_version,omitempty"`
	ApplicationVersionNum uint32   `protobuf:"varint,2,opt,name=application_version_num,json=applicationVersionNum,proto3" json:"application_version_num,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *ServiceApplicationInfoDto) Reset()         { *m = ServiceApplicationInfoDto{} }
func (m *ServiceApplicationInfoDto) String() string { return proto.CompactTextString(m) }
func (*ServiceApplicationInfoDto) ProtoMessage()    {}
func (*ServiceApplicationInfoDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9857153d4e6eb0b4, []int{2}
}

func (m *ServiceApplicationInfoDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceApplicationInfoDto.Unmarshal(m, b)
}
func (m *ServiceApplicationInfoDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceApplicationInfoDto.Marshal(b, m, deterministic)
}
func (m *ServiceApplicationInfoDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceApplicationInfoDto.Merge(m, src)
}
func (m *ServiceApplicationInfoDto) XXX_Size() int {
	return xxx_messageInfo_ServiceApplicationInfoDto.Size(m)
}
func (m *ServiceApplicationInfoDto) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceApplicationInfoDto.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceApplicationInfoDto proto.InternalMessageInfo

func (m *ServiceApplicationInfoDto) GetApplicationVersion() string {
	if m != nil {
		return m.ApplicationVersion
	}
	return ""
}

func (m *ServiceApplicationInfoDto) GetApplicationVersionNum() uint32 {
	if m != nil {
		return m.ApplicationVersionNum
	}
	return 0
}

type ServiceInstanceInfoDto struct {
	EndpointHost         string                     `protobuf:"bytes,1,opt,name=endpoint_host,json=endpointHost,proto3" json:"endpoint_host,omitempty"`
	EndpointPort         uint32                     `protobuf:"varint,2,opt,name=endpoint_port,json=endpointPort,proto3" json:"endpoint_port,omitempty"`
	ApplicationInfo      *ServiceApplicationInfoDto `protobuf:"bytes,3,opt,name=application_info,json=applicationInfo,proto3" json:"application_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ServiceInstanceInfoDto) Reset()         { *m = ServiceInstanceInfoDto{} }
func (m *ServiceInstanceInfoDto) String() string { return proto.CompactTextString(m) }
func (*ServiceInstanceInfoDto) ProtoMessage()    {}
func (*ServiceInstanceInfoDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9857153d4e6eb0b4, []int{3}
}

func (m *ServiceInstanceInfoDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceInstanceInfoDto.Unmarshal(m, b)
}
func (m *ServiceInstanceInfoDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceInstanceInfoDto.Marshal(b, m, deterministic)
}
func (m *ServiceInstanceInfoDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceInstanceInfoDto.Merge(m, src)
}
func (m *ServiceInstanceInfoDto) XXX_Size() int {
	return xxx_messageInfo_ServiceInstanceInfoDto.Size(m)
}
func (m *ServiceInstanceInfoDto) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceInstanceInfoDto.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceInstanceInfoDto proto.InternalMessageInfo

func (m *ServiceInstanceInfoDto) GetEndpointHost() string {
	if m != nil {
		return m.EndpointHost
	}
	return ""
}

func (m *ServiceInstanceInfoDto) GetEndpointPort() uint32 {
	if m != nil {
		return m.EndpointPort
	}
	return 0
}

func (m *ServiceInstanceInfoDto) GetApplicationInfo() *ServiceApplicationInfoDto {
	if m != nil {
		return m.ApplicationInfo
	}
	return nil
}

type ServiceBaseInfoListDto struct {
	AllServiceBaseInfoList []*ServiceBaseInfoDto `protobuf:"bytes,1,rep,name=all_service_base_info_list,json=allServiceBaseInfoList,proto3" json:"all_service_base_info_list,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}              `json:"-"`
	XXX_unrecognized       []byte                `json:"-"`
	XXX_sizecache          int32                 `json:"-"`
}

func (m *ServiceBaseInfoListDto) Reset()         { *m = ServiceBaseInfoListDto{} }
func (m *ServiceBaseInfoListDto) String() string { return proto.CompactTextString(m) }
func (*ServiceBaseInfoListDto) ProtoMessage()    {}
func (*ServiceBaseInfoListDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9857153d4e6eb0b4, []int{4}
}

func (m *ServiceBaseInfoListDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceBaseInfoListDto.Unmarshal(m, b)
}
func (m *ServiceBaseInfoListDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceBaseInfoListDto.Marshal(b, m, deterministic)
}
func (m *ServiceBaseInfoListDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceBaseInfoListDto.Merge(m, src)
}
func (m *ServiceBaseInfoListDto) XXX_Size() int {
	return xxx_messageInfo_ServiceBaseInfoListDto.Size(m)
}
func (m *ServiceBaseInfoListDto) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceBaseInfoListDto.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceBaseInfoListDto proto.InternalMessageInfo

func (m *ServiceBaseInfoListDto) GetAllServiceBaseInfoList() []*ServiceBaseInfoDto {
	if m != nil {
		return m.AllServiceBaseInfoList
	}
	return nil
}

type ServiceInstanceInfoListDto struct {
	AllServiceInstanceInfoList []*ServiceInstanceInfoDto `protobuf:"bytes,1,rep,name=all_service_instance_info_list,json=allServiceInstanceInfoList,proto3" json:"all_service_instance_info_list,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}                  `json:"-"`
	XXX_unrecognized           []byte                    `json:"-"`
	XXX_sizecache              int32                     `json:"-"`
}

func (m *ServiceInstanceInfoListDto) Reset()         { *m = ServiceInstanceInfoListDto{} }
func (m *ServiceInstanceInfoListDto) String() string { return proto.CompactTextString(m) }
func (*ServiceInstanceInfoListDto) ProtoMessage()    {}
func (*ServiceInstanceInfoListDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9857153d4e6eb0b4, []int{5}
}

func (m *ServiceInstanceInfoListDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceInstanceInfoListDto.Unmarshal(m, b)
}
func (m *ServiceInstanceInfoListDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceInstanceInfoListDto.Marshal(b, m, deterministic)
}
func (m *ServiceInstanceInfoListDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceInstanceInfoListDto.Merge(m, src)
}
func (m *ServiceInstanceInfoListDto) XXX_Size() int {
	return xxx_messageInfo_ServiceInstanceInfoListDto.Size(m)
}
func (m *ServiceInstanceInfoListDto) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceInstanceInfoListDto.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceInstanceInfoListDto proto.InternalMessageInfo

func (m *ServiceInstanceInfoListDto) GetAllServiceInstanceInfoList() []*ServiceInstanceInfoDto {
	if m != nil {
		return m.AllServiceInstanceInfoList
	}
	return nil
}

func init() {
	proto.RegisterType((*ServiceManagementModuleDto)(nil), "adm_dto.ServiceManagementModuleDto")
	proto.RegisterType((*ServiceBaseInfoDto)(nil), "adm_dto.ServiceBaseInfoDto")
	proto.RegisterType((*ServiceApplicationInfoDto)(nil), "adm_dto.ServiceApplicationInfoDto")
	proto.RegisterType((*ServiceInstanceInfoDto)(nil), "adm_dto.ServiceInstanceInfoDto")
	proto.RegisterType((*ServiceBaseInfoListDto)(nil), "adm_dto.ServiceBaseInfoListDto")
	proto.RegisterType((*ServiceInstanceInfoListDto)(nil), "adm_dto.ServiceInstanceInfoListDto")
}

func init() { proto.RegisterFile("grpc/adm_dto/service.proto", fileDescriptor_9857153d4e6eb0b4) }

var fileDescriptor_9857153d4e6eb0b4 = []byte{
	// 535 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x55, 0x36, 0xbe, 0x7a, 0xbb, 0xd2, 0x12, 0xa0, 0x94, 0x4e, 0xb0, 0x91, 0x49, 0xa8, 0x08,
	0xb5, 0x95, 0x36, 0xc4, 0x3b, 0x13, 0x0f, 0x4c, 0xd0, 0x09, 0x65, 0x1a, 0x68, 0xf0, 0x10, 0xb9,
	0x8e, 0xd7, 0x5a, 0xd8, 0xbe, 0xc1, 0x71, 0x26, 0xf6, 0x88, 0xc4, 0x13, 0xff, 0x86, 0xff, 0xc1,
	0x8f, 0x42, 0x75, 0xec, 0x7e, 0xa4, 0xe5, 0xd1, 0xe7, 0x9e, 0x9b, 0x73, 0xcf, 0xb9, 0x8e, 0xa1,
	0x3b, 0xd1, 0x19, 0x1d, 0x92, 0x54, 0x26, 0xa9, 0xc1, 0x61, 0xce, 0xf4, 0x15, 0xa7, 0x6c, 0x90,
	0x69, 0x34, 0x18, 0xde, 0x76, 0x70, 0xf4, 0x37, 0x80, 0xee, 0x59, 0x59, 0x1a, 0x11, 0x45, 0x26,
	0x4c, 0x32, 0x65, 0x46, 0x98, 0x16, 0x82, 0xbd, 0x35, 0x18, 0xee, 0x41, 0x5d, 0xda, 0x43, 0xa2,
	0x88, 0x64, 0x9d, 0x60, 0x3f, 0xe8, 0xd5, 0x62, 0x28, 0xa1, 0x53, 0x22, 0x59, 0xf8, 0x04, 0xdc,
	0x29, 0xf9, 0xc6, 0xae, 0x3b, 0x5b, 0xb6, 0x5e, 0x2b, 0x91, 0xf7, 0xec, 0x3a, 0x7c, 0x01, 0x2d,
	0x57, 0xe6, 0xca, 0x68, 0x4c, 0x0b, 0xca, 0x3a, 0xdb, 0x96, 0xd4, 0x2c, 0xf1, 0x13, 0x0f, 0x87,
	0xcf, 0xa1, 0xe9, 0xa9, 0x14, 0x55, 0x52, 0x68, 0xd1, 0xb9, 0x61, 0x99, 0x0d, 0xc7, 0xa4, 0xa8,
	0xce, 0xb5, 0x08, 0x77, 0xa1, 0xc6, 0x55, 0xca, 0x7e, 0x58, 0xc6, 0x4d, 0xcb, 0xb8, 0x63, 0x81,
	0x73, 0x2d, 0xa2, 0xdf, 0x5b, 0x10, 0x3a, 0x3b, 0xc7, 0x24, 0x67, 0x27, 0xea, 0x12, 0x9d, 0x0d,
	0xe7, 0xdf, 0x8e, 0xe9, 0x6c, 0x38, 0x68, 0x36, 0xe7, 0x33, 0xd8, 0xf1, 0x04, 0x6b, 0xb4, 0x34,
	0xe2, 0x9b, 0xac, 0xd3, 0x97, 0x70, 0xcf, 0x53, 0xaa, 0x5e, 0x5a, 0xae, 0xb0, 0x30, 0xd3, 0x83,
	0xd6, 0x9c, 0xec, 0xdd, 0x1c, 0x59, 0xee, 0x5d, 0xcf, 0x75, 0x76, 0x2e, 0xa0, 0x2d, 0xe7, 0xc1,
	0x27, 0x2e, 0x01, 0xc1, 0x73, 0xd3, 0x79, 0xb5, 0xbf, 0xdd, 0xab, 0x1f, 0x1e, 0x0c, 0xdc, 0xaa,
	0x06, 0xff, 0x5f, 0x53, 0xfc, 0x40, 0x56, 0xc0, 0x0f, 0x3c, 0x37, 0xd1, 0xaf, 0x00, 0x1e, 0xbb,
	0xa6, 0x37, 0x59, 0x26, 0x38, 0x25, 0x86, 0xa3, 0xf2, 0x99, 0x0c, 0xe1, 0x3e, 0x59, 0xa0, 0xc9,
	0x15, 0xd3, 0x39, 0x47, 0xe5, 0xb2, 0x09, 0x97, 0x4a, 0x9f, 0xca, 0x4a, 0xf8, 0x1a, 0x1e, 0x6d,
	0x68, 0x48, 0x54, 0x21, 0x6d, 0x5c, 0x8d, 0xf8, 0xe1, 0x7a, 0xd3, 0x69, 0x21, 0xa3, 0x3f, 0x01,
	0xb4, 0xcf, 0x7c, 0x40, 0xb9, 0x21, 0x8a, 0xce, 0xf7, 0x72, 0x00, 0x0d, 0xa6, 0xd2, 0x0c, 0xb9,
	0x32, 0xc9, 0x14, 0x73, 0xe3, 0xd4, 0x77, 0x3c, 0xf8, 0x0e, 0x73, 0xb3, 0x42, 0xca, 0x50, 0x1b,
	0xa7, 0x36, 0x27, 0x7d, 0x44, 0x6d, 0xc2, 0x11, 0xb4, 0x96, 0x87, 0xe3, 0xea, 0x12, 0xed, 0x72,
	0xea, 0x87, 0x51, 0x35, 0xc0, 0xf5, 0x2c, 0xe2, 0x26, 0x59, 0xc5, 0xa2, 0xef, 0xf3, 0x91, 0xfd,
	0x35, 0x9a, 0x25, 0x3a, 0x1b, 0xf9, 0x33, 0x74, 0x89, 0x10, 0x89, 0xdf, 0xee, 0x98, 0xe4, 0xcc,
	0xaa, 0x95, 0x3b, 0x0b, 0xec, 0xce, 0x76, 0xab, 0x92, 0x4b, 0x77, 0x31, 0x6e, 0x13, 0x21, 0x36,
	0x7c, 0x3b, 0xfa, 0xb9, 0xf8, 0x13, 0x97, 0x63, 0xf2, 0xba, 0x14, 0x9e, 0x2e, 0xeb, 0x72, 0x47,
	0x59, 0xd3, 0xde, 0xab, 0x6a, 0x57, 0x32, 0x8f, 0xbb, 0x0b, 0xfd, 0xaa, 0xce, 0xf1, 0xd7, 0x2f,
	0x17, 0x13, 0x6e, 0xa6, 0xc5, 0x78, 0x40, 0x51, 0x0e, 0x05, 0x93, 0xa8, 0xfa, 0x54, 0x60, 0x91,
	0xf6, 0x9d, 0xee, 0x0a, 0x96, 0x92, 0x7c, 0x3a, 0x46, 0xa2, 0xd3, 0xcd, 0x68, 0x9f, 0xa2, 0x94,
	0xa8, 0xfc, 0x0b, 0x34, 0xbe, 0x65, 0x9f, 0x9e, 0xa3, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2e,
	0xec, 0xdc, 0x3d, 0x98, 0x04, 0x00, 0x00,
}
